export const LOGIN_USER = "LOGIN_USER";

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_ALL_USER = "GET_ALL_USER";
export const SINGLE_USER = "SINGLE_USER";

export const ADD_DEPT_SUCCESS = "ADD_DEPT_SUCCESS";
export const DELETE_DEPT_SUCCESS = "DELETE_DEPT_SUCCESS";
export const GET_ALL_DEPT = "GET_ALL_DEPT";

export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";